--Simplified Chinese localization by haidaodou
if (GetLocale()~="zhCN") then return end
local _, me = ...
local L = me.L

L["addtofav"] = "添加到收藏夹"
L["alt"] = "ALT"
L["autoloot"] = " (+ 自动拾取)"
L["bothfactions"] = "显示两边阵营专业技能和冷却"
L["cds"] = "冷却状态"
L["ctrl"] = "CTRL"
L["databaseempty"] = "空数据库"
L["deletechartooltip"] = "|cffff0000注意:|r 清除本角色所有设置!"
L["favorites"] = "收藏夹"
L["filter"] = "隐藏专业技能"
L["infight"] = "你在战斗中!"
L["knowallrecipes"] = "|cffffcf00所有配方都已学会|r"
L["leftclick"] = "左键点击"
L["linktome"] = "发送到自身"
L["linktoother"] = "发送到聊天框"
L["nocds"] = "准备就绪"
L["nofavorites"] = [=[还没有添加收藏项目!
打开专业技能窗口,右键点击你的技能来添加或删除项目.]=]
L["nomats"] = "没有足够的材料"
L["openLastProfessionWindow"] = "打开最后一次打开过的专业技能窗口"
L["openmenu"] = "打开选项菜单"
L["otherchar"] = "其他角色"
-- L["pandaria_research"] = "Pandaria research"
L["professions"] = "专业技能"
L["quicklaunch"] = "快速启动"
L["quicklauncher"] = "独立显示于信息条"
L["relog"] = "需要重载插件!"
L["removefromfav"] = "从收藏夹移除"
L["resetcds"] = "重置冷却"
L["rightclick"] = "右键点击"
L["settings"] = "设置"
L["shift"] = "Shift"
L["ShowAllTooltips"] = "显示所有鼠标提示"
L["showbuttons"] = "按键说明"
L["showcds"] = "冷却状态"
L["showfavorites"] = "显示收藏夹"
L["ShowIfYouCanCraftThisInItemTooltips"] = "如果你能制造,则显示于物品提示中"
L["tooltips"] = "鼠标提示"
L["trainer"] = "训练师"
L["trainerdisabled"] = "禁用训练师扩展界面"
L["transmute"] = "炼金术: 转化"
L["visityourtrainer"] = "请访问你的 |cff00ff00%s|r 训练师"

