--Traditional Chinese localization by haidaodou
if (GetLocale()~="zhTW") then return end
local _, me = ...
local L = me.L

L["addtofav"] = "添加到收藏夾"
L["alt"] = "ALT"
L["autoloot"] = " (+ 自動拾取)"
L["bothfactions"] = "顯示兩邊陣營的專業技能和冷卻"
L["cds"] = "冷卻狀態"
L["ctrl"] = "CTRL"
L["databaseempty"] = "空數據庫"
L["deletechartooltip"] = "|cffff0000注意:|r 清除本角色所有設置!"
L["favorites"] = "收藏夾"
L["filter"] = "隱藏專業技能"
L["infight"] = "你在戰鬥中!"
L["knowallrecipes"] = "|cffffcf00所有配方都已學會|r"
L["leftclick"] = "左鍵點擊"
L["linktome"] = "發送到自身"
L["linktoother"] = "發送到聊天框"
L["nocds"] = "準備就緒"
L["nofavorites"] = [=[還沒有收藏項目!
打開你的專業技能窗口,右鍵點擊你的技能來添加或刪除項目.]=]
L["nomats"] = "沒有足夠的原料"
L["openLastProfessionWindow"] = "打開最後一次打開過的專業技能窗口"
L["openmenu"] = "打開選項菜單"
L["otherchar"] = "其他角色"
-- L["pandaria_research"] = "Pandaria research"
L["professions"] = "專業技能"
L["quicklaunch"] = "快速啟動"
L["quicklauncher"] = "獨立顯示於信息條"
L["relog"] = "需要重新加載插件"
L["removefromfav"] = "從收藏夾移除"
L["resetcds"] = "重置冷卻"
L["rightclick"] = "右鍵點擊"
L["settings"] = "設置"
L["shift"] = "Shift"
L["ShowAllTooltips"] = "顯示所有訊息提示"
L["showbuttons"] = "按鍵說明"
L["showcds"] = "冷卻狀態"
L["showfavorites"] = "顯示收藏夾"
L["ShowIfYouCanCraftThisInItemTooltips"] = "如果你能製造,則顯示於物品提示中"
L["tooltips"] = "滑鼠訊息提示"
L["trainer"] = "訓練師"
L["trainerdisabled"] = "禁用訓練師擴展介面"
L["transmute"] = "煉金術: 轉化"
L["visityourtrainer"] = "請訪問你的 |cff00ff00%s|r 訓練師"

