-- Daily Global Check
-- Localization

local addonName, addonTable = ...

if GetLocale() == "itIT" then -- ita
 addonTable.L = {
  ["opt_main"] = "Opzioni",
  ["opt_questtype"] = "Mostra tipo di quest",
  ["opt_prefix"] = "Mostra prefisso",
  ["opt_zonename"] = "Mostra il nome della zona",
  ["opt_suffix"] = "Mostra suffisso",
  ["opt_coords"] = "Mostra coordinate",
  ["opt_minimap"] = "Mostra pulsante sulla minimappa",
  ["opt_map"] = "Mostra icone sulla mappa globale",
  ["tomtom_button"] = "Imposta waypoints su TomTom",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - Waypoint aggiunto a TomTom",
  ["notitle"] = "<nessun titolo>",
  ["availablelists"] = "Liste Disponibili",
  ["lclicktoopen"] = "Click sinistro per aprire il frame principale",
  ["rclicktoopen"] = "Click destro per aprire il menù di selezione rapida",
  ["namemissing"] = "<nome mancante>",
  ["questdatamissing"] = "<dati quest mancanti>",
  -- 1001
  ["add"]              = "Aggiungi",
  ["rem"]              = "Rimuovi",
  ["customlist"]       = "Lista Personalizzata",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - Devi inserire l'ID e il nome della quest",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - La quest e' gia' in lista.",
  ["questwindow"] = "- Seleziona la posizione -",
  ["nolist"] = "Nessuna lista selezionata",
  ["remmenuheader"] = "- Seleziona la quest da eliminare -",
  ["added"] = "aggiunto",
  ["deleted"] = "eliminato",
  ["buildframe"] = "Modifica Lista Personalizzata",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Nome Quest",
  ["b_prefix"] = "Prefisso (opzionale)",
  ["b_suffix"] = "Suffisso (opzionale)",
  ["addbtntooltip"] = "Aggiungi la quest selezionata alla tua Lista Personalizzata di Daily Global Check",
  ["opt_showquestbtn"] = "Mostra il pulsante 'Aggiungi quest alla Lsita Personalizzata' nel registro missioni",
 }
 elseif GetLocale() == "zhTW" then  -- traditional chinese
 addonTable.L = {
  ["opt_main"] = "選項",
  ["opt_questtype"] = "顯示任務類型",
  ["opt_prefix"] = "顯示前綴",
  ["opt_zonename"] = "顯示區域名稱",
  ["opt_suffix"] = "顯示後綴",
  ["opt_coords"] = "顯示坐標",
  ["opt_minimap"] = "顯示小地圖按鈕",
  ["opt_map"] = "顯示世界地圖圖標",
  ["tomtom_button"] = "設置TomTom航點",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - 航點加入到TomTom",
  ["notitle"] = "<沒有標題>",
  ["availablelists"] = "可用列表",
  ["lclicktoopen"] = "左鍵單擊打開主框架",
  ["rclicktoopen"] = "右鍵單擊打開快速列表選擇菜單",
  ["namemissing"] = "<名字丟失>",
  ["questdatamissing"] = "<任務數據丟失>",
 -- 1001
  ["add"]              = "Add",
  ["rem"]              = "Remove",
  ["customlist"]       = "Custom List",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - You need to enter either the quest ID and its name.",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - This quest is already in list.",
  ["questwindow"] = "- Select quest position -",
  ["nolist"] = "No list selected",
  ["remmenuheader"] = "- Select the quest to remove -",
  ["added"] = "added",
  ["deleted"] = "deleted",
  ["buildframe"] = "Modify Custom List",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Quest Name",
  ["b_prefix"] = "Prefix (optional)",
  ["b_suffix"] = "Suffix (optional)",
  ["addbtntooltip"] = "Add the selected quest to your Daily Global Check Custom List",
  ["opt_showquestbtn"] = "Show the 'Add quest to Custom List' button in the Quest Log Frame",
 }
elseif GetLocale() == "zhCN" then -- simplified chinese
 addonTable.L = {
  ["opt_main"] = "选项",
  ["opt_questtype"] = "显示任务类型",
  ["opt_prefix"] = "显示前缀",
  ["opt_zonename"] = "显示区域名称",
  ["opt_suffix"] = "显示后缀",
  ["opt_coords"] = "显示坐标",
  ["opt_minimap"] = "显示小地图按钮",
  ["opt_map"] = "显示世界地图图标",
  ["tomtom_button"] = "设置TomTom航点",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - 航点加入到TomTom",
  ["notitle"] = "<没有标题>",
  ["availablelists"] = "可用列表",
  ["lclicktoopen"] = "左键单击打开主框架",
  ["rclicktoopen"] = "右键单击打开快速列表选择菜单",
  ["namemissing"] = "<名字丢失>",
  ["questdatamissing"] = "<任务数据丢失>",
 -- 1001
  ["add"]              = "Add",
  ["rem"]              = "Remove",
  ["customlist"]       = "Custom List",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - You need to enter either the quest ID and its name.",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - This quest is already in list.",
  ["questwindow"] = "- Select quest position -",
  ["nolist"] = "No list selected",
  ["remmenuheader"] = "- Select the quest to remove -",
  ["added"] = "added",
  ["deleted"] = "deleted",
  ["buildframe"] = "Modify Custom List",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Quest Name",
  ["b_prefix"] = "Prefix (optional)",
  ["b_suffix"] = "Suffix (optional)",
  ["addbtntooltip"] = "Add the selected quest to your Daily Global Check Custom List",
  ["opt_showquestbtn"] = "Show the 'Add quest to Custom List' button in the Quest Log Frame",
 }
elseif GetLocale() == "ruRU" then -- Russian
 addonTable.L = {
  ["opt_main"] = "Настройки",
  ["opt_questtype"] = "Отображать тип квеста",
  ["opt_prefix"] = "Отображать префикс",
  ["opt_zonename"] = "Отображать название локации",
  ["opt_suffix"] = "Отображать суффикс",
  ["opt_coords"] = "Отображать координаты",
  ["opt_minimap"] = "Включить кнопку у миникарты",
  ["opt_map"] = "Показывать иконки на карте мира",
  ["tomtom_button"] = "Устанавливать направления в TomTom",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - в TomTom добавлено направление.",
  ["notitle"] = "<no title>",
  ["availablelists"] = "Доступные списки",
  ["lclicktoopen"] = "Нажмите левую кнопку мыши, чтобы открыть основное окно",
  ["rclicktoopen"] = "Нажмите правую кнопку мыши, чтобы открыть меню быстрого выбора",
  ["namemissing"] = "Нет имени",
  ["questdatamissing"] = "Нет данных квеста",
 -- 1001
  ["add"]              = "Add",
  ["rem"]              = "Remove",
  ["customlist"]       = "Custom List",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - You need to enter either the quest ID and its name.",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - This quest is already in list.",
  ["questwindow"] = "- Select quest position -",
  ["nolist"] = "No list selected",
  ["remmenuheader"] = "- Select the quest to remove -",
  ["added"] = "added",
  ["deleted"] = "deleted",
  ["buildframe"] = "Modify Custom List",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Quest Name",
  ["b_prefix"] = "Prefix (optional)",
  ["b_suffix"] = "Suffix (optional)",
  ["addbtntooltip"] = "Add the selected quest to your Daily Global Check Custom List",
  ["opt_showquestbtn"] = "Show the 'Add quest to Custom List' button in the Quest Log Frame",
 }
elseif GetLocale() == "deDE" then -- German
 addonTable.L = {
  ["opt_main"] = "Einstellungen",
  ["opt_questtype"] = "Zeige Quest Typ",
  ["opt_prefix"] = "Zeige Vorsilbe",
  ["opt_zonename"] = "Zeige Zonen Name",
  ["opt_suffix"] = "Zeige Nachsilbe",
  ["opt_coords"] = "Zeige Koordinaten",
  ["opt_minimap"] = "Zeige Minikarten Knopf",
  ["opt_map"] = "Zeige Weltkarten Symbole",
  ["tomtom_button"] = "Setze TomTom Wegpunkte",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - Wegpunkt für TomTom hinzugefügt",
  ["notitle"] = "<kein titel>",
  ["availablelists"] = "Verfügbare Listen",
  ["lclicktoopen"] = "Links-klick zum öffnen des Hauptfensters",
  ["rclicktoopen"] = "Rechts-klick zum öffnen des Schnellauswahlmenüs.",
  ["namemissing"] = "<name fehlt>",
  ["questdatamissing"] = "<quest daten fehlen>",
 -- 1001
  ["add"]              = "Hinzufügen",
  ["rem"]              = "Entfernen",
  ["customlist"]       = "Eigene Liste",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - Du must entweder die Quest ID und ihren Namen eingeben.",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - Diese Quest ist schon in der Liste.",
  ["questwindow"] = "- Wähle die Quest Position -",
  ["nolist"] = "Keine Liste ausgewählt",
  ["remmenuheader"] = "- Wähle die Quest zum entfernen -",
  ["added"] = "zusätzlich",
  ["deleted"] = "gelöscht",
  ["buildframe"] = "Bearbeite Eigene Liste",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Quest Name",
  ["b_prefix"] = "Vorsilbe (optional)",
  ["b_suffix"] = "Nachsilbe (optional)",
  ["addbtntooltip"] = "Füge die ausgewählte Quest deiner eigenen Daily Global Check Liste hinzu.",
  ["opt_showquestbtn"] = "Zeige die Schaltfläche 'Füge Quest zur Eigenen Liste hinzu' im Questbuch an.",
 }
else -- eng
 addonTable.L = {
  ["opt_main"] = "Options",
  ["opt_questtype"] = "Show quest type",
  ["opt_prefix"] = "Show prefix",
  ["opt_zonename"] = "Show zone name",
  ["opt_suffix"] = "Show suffix",
  ["opt_coords"] = "Show coordinates",
  ["opt_minimap"] = "Show minimap button",
  ["opt_map"] = "Show world map icons",
  ["tomtom_button"] = "Set TomTom waypoints",
  ["s_tomtomset"] = "|cff11DDFFDaily Global Check|r - Waypoint added to TomTom",
  ["notitle"] = "<no title>",
  ["availablelists"] = "Available Lists",
  ["lclicktoopen"] = "Left-click to open the main frame",
  ["rclicktoopen"] = "Right-click to open the quick list selection menu",
  ["namemissing"] = "<name missing>",
  ["questdatamissing"] = "<quest data missing>",
 -- 1001
  ["add"]              = "Add",
  ["rem"]              = "Remove",
  ["customlist"]       = "Custom List",
  ["bf_err1"]          = "|cff11DDFFDaily Global Check|r - You need to enter either the quest ID and its name.",
  ["bf_err2"]          = "|cff11DDFFDaily Global Check|r - This quest is already in list.",
  ["questwindow"] = "- Select quest position -",
  ["nolist"] = "No list selected",
  ["remmenuheader"] = "- Select the quest to remove -",
  ["added"] = "added",
  ["deleted"] = "deleted",
  ["buildframe"] = "Modify Custom List",
  ["b_questid"] = "Quest ID",
  ["b_questname"] = "Quest Name",
  ["b_prefix"] = "Prefix (optional)",
  ["b_suffix"] = "Suffix (optional)",
  ["addbtntooltip"] = "Add the selected quest to your Daily Global Check Custom List",
  ["opt_showquestbtn"] = "Show the 'Add quest to Custom List' button in the Quest Log Frame",
 }
end