--[[ shared ]]
L["Alt+Click"] = "" -- friends, guild
L["Are you sure you want to Reload the UI?"] = "" -- gamemenu, stuff
L["Bags"] = "" -- bags, durability
L["Broker to allow you to do...Stuff! Switch to windowed mode, reload ui, logout and quit."] = "" -- gamemenu, stuff
L["Broker to show, equip, delete, update and save equipment sets"] = "" -- equipment, surprise
L["Character"] = "" -- durability, friends, guild
L["Click"] = "" -- calendar, durability, equipment, fps, friends, gold, guild, nameplates, questlog, tracking, volume, xp
L["Ctrl+Click"] = "" -- equipment, fps
L["Delete a set"] = "" -- equipment, fps
L["Equipment"] = "" -- chatcommand, equipment
L["Friendly"] = "" -- durability, gps
L["Gold coloring"] = "" -- optionspanel, bags, durability, gold
L["Guild"] = "" -- guild, xp
L["Left-click"] = "" -- bags, clock, currency, dualspec, friends, gamemenu, gps, guild, mem, stuff
L["Level"] = "" -- clock, friends, guild, questlog
L["Logout"] = "" -- gamemenu, stuff
L["No data found"] = "" -- durability, xp
L["No sets found"] = "" -- chatcommand, equipment
L["None"] = "" -- optionspanel, nameplates
L["Notes"] = "" -- friends, guild
L["Open calendar"] = "" -- calendar, clock
L["Open currency pane"] = "" -- currency, gold
L["Options"] = "" -- core, optionspanel, durability
L["Precision"] = "" -- gps, speed
L["Quit game"] = "" -- gamemenu, stuff
L["Reload UI"] = "" -- optionspanel, gamemenu, stuff
L["Right-click"] = "" -- bags, clock, currency, dualspec, gamemenu, gold, gps, guild, latency, mem, stuff, xp
L["Shift+Click"] = "" -- equipment, fps
L["Shift+Left-click"] = "" -- clock, gamemenu, stuff
L["Shift+Right-click"] = "" -- clock, mem
L["Unknown"] = "" -- bags, framenames
L["Update/save a set"] = "" -- equipment, fps
L["Use colors instead of icons for gold, silver and copper"] = "" -- optionspanel, bags, durability, gold
L["XP"] = "" -- guild, xp
L["Zone"] = "" -- friends, gps, guild

--[[ bags ]]
L["All qualities"] = ""
L["All qualities (+ vendor price)"] = ""
L["Broker to show filled, total and free count of blag slots"] = ""
L["Choose your favorite"] = ""
L["Count"] = ""
L["Critical low free slots"] = ""
L["Display a list of item qualities"] = ""
L["Free slots"] = ""
L["Non empty qualities"] = ""
L["Non empty qualities (+ vendor price)"] = ""
L["Open bags"] = ""
L["Quality"] = ""
L["Quality list"] = ""
L["Select the maximum free slot count to coloring in red."] = ""
L["Select the maximum free slot count to coloring in yellow."] = ""
L["Show quality"] = ""
L["Switch display"] = ""
L["Total slots"] = ""
L["Vendor price"] = ""
L["Warn low free slots"] = ""
L["free"] = ""
L["poor and common"] = ""
L["poor and common (+ vendor price)"] = ""
L["poor only"] = ""
L["poor only (+ vendor price)"] = ""

--[[ calendar ]]
L["Broker to show invitations"] = ""
L["Calendar"] = ""
L["Hide Blizzard's minimap calendar button"] = ""
L["Hide calendar button"] = ""
L["Invitation"] = ""
L["Invitations"] = ""
L["No invitations found"] = ""
L["Reduce the broker text to a number without text"] = ""
L["Shorter Broker"] = ""

--[[ chatcommand ]]
L["Available Sets:"] = ""
L["Broker_Everything will use the new setting on next reload."] = ""
L["Cfg"] = ""
L["Change number of displayed addons in module memory."] = ""
L["Chat command list for /be & /broker_everything"] = ""
L["Data modules:"] = ""
L["Disabling %s on next reload."] = ""
L["Enable/disable tooltip scaling."] = ""
L["Enabling %s on next reload."] = ""
L["Equip a set."] = ""
L["Hide/Show tooltip hint."] = ""
L["Info"] = ""
L["List of available modules with his status"] = ""
L["Name of Equipmentset are invalid"] = ""
L["Open AllInOne panel"] = ""
L["Open broker panel"] = ""
L["Open options panel"] = ""
L["Reset all module settings"] = ""
L["Showing a maximum of %d addons."] = ""
L["Showing all addons."] = ""
L["Switch between global and per character saved settings"] = ""
L["Usage: /be equip <SetName>"] = ""

--[[ clock ]]
L["12 / 24 hours mode"] = ""
L["24 hours mode"] = ""
L["Broker to show realm or local time"] = ""
L["Clock"] = ""
L["Display the time with seconds in broker button and tooltip"] = ""
L["Local Time"] = ""
L["Local or server time"] = ""
L["Open time manager"] = ""
L["Playtime"] = ""
L["Server Time"] = ""
L["Session"] = ""
L["Show seconds"] = ""
L["Switch between local and server time in broker button"] = ""
L["Switch between time format 24 hours and 12 hours with AM/PM"] = ""
L["Total"] = ""
L["UTC Time"] = ""

--[[ core ]]
L["Warning"] = ""
L["saved variables have been reset."] = ""

--[[ currency ]]
L["Add a currency"] = ""
L["Auto"] = ""
L["Broker to show your different currencies."] = ""
L["Currencies in Title"] = ""
L["Currency"] = ""
L["Currency in title - menu"] = ""
L["Display as favorite selected currencies only."] = ""
L["Favorite mode"] = ""
L["Left"] = ""
L["Over"] = ""
L["Place"] = ""
L["Remove"] = ""
L["Replace the curreny"] = ""
L["Right"] = ""
L["Second tooltip"] = ""
L["Under"] = ""
L["Where does the second tooltip for a single currency are displayed from the first tooltip"] = ""
L["display the content of the tooltip shorter"] = ""
L["short Tooltip"] = ""

--[[ dualspec ]]
L["%d unspent talent"] = ""
L["%d unspent talents"] = ""
L["Active"] = ""
L["Broker to show and switch your character specializations"] = ""
L["Dualspec"] = ""
L["No Spec!"] = ""
L["No specialisation found"] = ""
L["Open talents pane"] = ""
L["Switch spec."] = ""
L["Talents"] = ""
L["Unspent talents: %d"] = ""

--[[ durability ]]
L["(session only)"] = ""
L["Auto repair"] = ""
L["Automaticly repair your equipment on opening a merchant with repair option."] = ""
L["Average"] = ""
L["Broker format"] = ""
L["Broker to show durability of your gear and estimated repair costs."] = ""
L["Choose how much entries the list of repair costs can have."] = ""
L["Choose the date format if used in the list of repair costs"] = ""
L["Choose your favorite color set in which the percent text in broker should be displayed."] = ""
L["Choose your favorite display format for the broker button."] = ""
L["Date format"] = ""
L["Display a list of the last repair costs in tooltip"] = ""
L["Display the lowest item durability in broker."] = ""
L["Durability"] = ""
L["Exalted"] = ""
L["Honoured"] = ""
L["Last %d repair costs"] = ""
L["List of repair costs"] = ""
L["Lowest durability"] = ""
L["Lowest item"] = ""
L["Max. list entries"] = ""
L["Neutral"] = ""
L["Open character info"] = ""
L["Percent color set"] = ""
L["Repair by Guild"] = ""
L["Repair cost"] = ""
L["Reputation discounts"] = ""
L["Reset last repairs"] = ""
L["Revered"] = ""
L["Save repair costs"] = ""
L["Save the list of repair costs over the session"] = ""
L["Show discount"] = ""
L["Show list of reputation discounts in tooltip"] = ""
L["Use guild money"] = ""
L["Use guild money on auto repair if you can"] = ""

--[[ equipment ]]
L["Enable it from the character pane"] = ""
L["Equip a set"] = ""
L["Equipment manager is not enabled"] = ""
L["No equipment sets found"] = ""
L["Open equipment manager"] = ""
L["Unknown Set"] = ""

--[[ fps ]]
L["Broker to show your frames per second."] = ""
L["Current"] = ""
L["FPS"] = ""
L["Max."] = ""
L["Min."] = ""
L["No set found"] = ""
L["Open graphics menu"] = ""
L["Open graphics set manager"] = ""
L["Right-Click"] = ""
L["Use a set"] = ""

--[[ framenames ]]
L["Broker to show names of frames under the mouse."] = ""
L["Framenames"] = ""

--[[ friends ]]
L["BattleNet"] = ""
L["BattleTag"] = ""
L["Broker to show you which friends are online."] = ""
L["Characters"] = ""
L["Disable displaying game icons and use game shortcut instead of"] = ""
L["Disable game icons"] = ""
L["Display guild name in tooltip (BattleNet friends only)"] = ""
L["Faction"] = ""
L["Friends"] = ""
L["Game"] = ""
L["Invite a friend"] = ""
L["My current broadcast message"] = ""
L["No friends online."] = ""
L["Open friends roster"] = ""
L["Real ID"] = ""
L["Realm"] = ""
L["Show guild name"] = ""
L["Split Characters and BattleNet-Friends in Tooltip"] = ""
L["Split Characters and BattleNet-Friends on Broker Button"] = ""
L["Split friends|nin Tooltip"] = ""
L["Split friends|non Broker"] = ""
L["Whisper with a friend"] = ""

--[[ gamemenu ]]
L["As tooltip title"] = ""
L["Cancel ticket"] = ""
L["Disable Click options"] = ""
L["Disable the click options on broker button"] = ""
L["Edit ticket"] = ""
L["Game Menu"] = ""
L["Hide section 2"] = ""
L["Hide section 2 in tooltip"] = ""
L["Hide section 3"] = ""
L["Hide section 3 in tooltip"] = ""
L["Set your own Title instead of 'Game Menu'"] = ""
L["Show GMTicket"] = ""
L["Show GMTickets in tooltip and average wait time in broker button"] = ""
L["Use custom title as tooltip title"] = ""
L["custom Title"] = ""

--[[ gold ]]
L["Broker to show gold information. Shows gold amounts for characters on the same ns.realm and faction and the amount made or lost for the session."] = ""
L["Gold"] = ""
L["Gold information"] = ""
L["Remove entry"] = ""
L["Session loss"] = ""
L["Session profit"] = ""
L["Total Gold"] = ""

--[[ gps ]]
L["Arena"] = ""
L["Broker to show the name of the current Zone and the co-ordinates."] = ""
L["Broker to show the name of the current zone."] = ""
L["Broker to show your current co-ordinates within the zone."] = ""
L["Change how much digits display after the dot."] = ""
L["Co-ordinates"] = ""
L["Co-ordinates indeterminable"] = ""
L["Co-ordination format"] = ""
L["Combat"] = ""
L["Contested"] = ""
L["Display in broker zone and subzone if exists or one of it."] = ""
L["Display the transport menu without names of spells and items behind the icons."] = ""
L["Display zone names"] = ""
L["GPS"] = ""
L["GPS / Location / ZoneText"] = ""
L["Hostile"] = ""
L["How would you like to view co-ordinations."] = ""
L["Inn"] = ""
L["Items"] = ""
L["Location"] = ""
L["No spells or items found"] = ""
L["Open World map"] = ""
L["Open transport menu"] = ""
L["Sanctuary"] = ""
L["Short transport menu"] = ""
L["Sorry"] = ""
L["Subzone"] = ""
L["Zone status"] = ""
L["ZoneText"] = ""

--[[ guild ]]
L["Applicant"] = ""
L["Broker to show guild information. Guild members currently online, MOTD, guild xp etc."] = ""
L["Comment"] = ""
L["Damage"] = ""
L["Display guild level and xp (percent) in broker button"] = ""
L["Display mobile chatter with own table in tooltip"] = ""
L["Enable/Disable the display of Guild Reputation in the Guild data broker tooltip."] = ""
L["Enable/Disable the display of Guild XP in the Guild data broker tooltip."] = ""
L["Expired"] = ""
L["Healer"] = ""
L["Invite a member"] = ""
L["MobileChat"] = ""
L["MotD:"] = ""
L["No Guild"] = ""
L["No Text"] = ""
L["Officer notes"] = ""
L["Open guild roster"] = ""
L["Open little option menu"] = ""
L["Option menu"] = ""
L["Professions"] = ""
L["Rank"] = ""
L["Rep"] = ""
L["Roles"] = ""
L["Separate mobile chatter"] = ""
L["Show Guild Message of the Day in tooltip"] = ""
L["Show Guild MotD"] = ""
L["Show Guild XP"] = ""
L["Show applicants"] = ""
L["Show applicants in broker and tooltip"] = ""
L["Show guild lvl&xp in broker"] = ""
L["Show guild reputation"] = ""
L["Show member professions in tooltip"] = ""
L["Show mobile chatter in tooltip"] = ""
L["Show modile chatter"] = ""
L["Show professions"] = ""
L["Show realm name"] = ""
L["Tank"] = ""
L["Whisper with a member"] = ""

--[[ latency ]]
L["Alt+Right-click"] = ""
L["Broker to show your current latency. Can be configured to show both Home and/or World latency."] = ""
L["Ctrl+Right-click"] = ""
L["Enable/Disable the display of the latency to the home realm"] = ""
L["Enable/Disable the display of the latency to the world realms"] = ""
L["Home"] = ""
L["Home latency on/off"] = ""
L["Latency"] = ""
L["Suffix coloring on/off"] = ""
L["World"] = ""
L["World latency on/off"] = ""
L["show home"] = ""
L["show world"] = ""

--[[ mail ]]
L["Broker to alert you if you have mail."] = ""
L["Display a list of chars on all realms with there mail counts and 3 lowest days before return to sender. Chars with empty mail box aren't displayed."] = ""
L["Enable to play a sound on receiving a new mail message. Default is off"] = ""
L["Hide minimap mail icon"] = ""
L["Last 3 new mails"] = ""
L["Leave in mailbox"] = ""
L["List mails on chars"] = ""
L["Mail"] = ""
L["Mail from"] = ""
L["New mail"] = ""
L["No Mail"] = ""
L["No data"] = ""
L["Play sound on new mail"] = ""
L["Stored mails"] = ""
L["mails"] = ""

--[[ mem ]]
L["Addon"] = ""
L["All"] = ""
L["Broker to show how much memory are consumed through your addons."] = ""
L["Collect garbage"] = ""
L["Collecting Garbage..."] = ""
L["Memory"] = ""
L["Memory Usage"] = ""
L["No addon manager found. Tried OptionHouse, ACP, stAddonManager and Ampere."] = ""
L["Open Addon Control Panel"] = ""
L["Open OptionHouse"] = ""
L["Open interface options"] = ""
L["Open stAddonManager"] = ""
L["Select the maximum number of addons to display, otherwise drag to 'All'."] = ""
L["Total Memory usage"] = ""

--[[ nameplates ]]
L["Broker to allow you to toggle the various nameplates. Eg, friendly or hostile."] = ""
L["Creations"] = ""
L["Hidden"] = ""
L["Misc"] = ""
L["Nameplates"] = ""
L["Names"] = ""
L["Names/Nameplates on/off"] = ""
L["Shown"] = ""

--[[ optionspanel ]]
L["Allows you to adjust the display options."] = ""
L["Broker as Minimap Buttons"] = ""
L["Change the color of the icons"] = ""
L["Choose an custom iconset"] = ""
L["Enable/Disable Class colouring of the information display suffixes. (eg, ms, fps etc)"] = ""
L["Enable/Disable the showing of a global Broker_Everything profile across all of your characters."] = ""
L["General Options"] = ""
L["Icon color"] = ""
L["Iconsets"] = ""
L["Module Options"] = ""
L["Reloads the UI. You must do this to apply any changes in module activation."] = ""
L["Remove all selections from modules"] = ""
L["Reset"] = ""
L["Resets the Broker_Everything Defaults and Reloads the UI."] = ""
L["Scale the tooltips with your UIScale. Default is off"] = ""
L["Select all"] = ""
L["Select all modules"] = ""
L["Select none"] = ""
L["Select the listed broker to enable/disable. You must Reload UI for any changes to apply."] = ""
L["Show hints"] = ""
L["Show hints in tooltips."] = ""
L["Suffix Colouring"] = ""
L["The screen capture mode replaces all characters of a name with wildcards (*) without the first. Your chars in XP, your friends battleTags/RealID and there character names and the character names in your guild and there notes."] = ""
L["Tooltip Scaling"] = ""
L["Use Blizz Locales"] = ""
L["Use Blizzard's localizations. Thats translates only a part auf single names. Please report problems, wrong translations and more. Any feedback are welcome."] = ""
L["Use LibDBIcon to add Broker to Minimap"] = ""
L["Use global profile"] = ""
L["Use prefix"] = ""
L["Use prefix 'BE..' on module registration at LibDataBroker. This fix problems with other addons with same broker names but effect your current settings in panel addons like Bazooka or Titan Panel."] = ""
L["screen capture mode"] = ""

--[[ questlog ]]
L["Active quests"] = ""
L["Broker to show count of quests in your questlog and quest titles in tooltip."] = ""
L["Choose your favorite website for further informations to a quest."] = ""
L["Completed quests"] = ""
L["Failed quests"] = ""
L["Fav. website"] = ""
L["Open QuestLog and select quest"] = ""
L["Quest Log"] = ""
L["QuestId"] = ""
L["Show quest id's"] = ""
L["Show quest id's in tooltip."] = ""
L["Show quest items"] = ""
L["Show quest items in tooltip."] = ""
L["share"] = ""

--[[ speed ]]
L["How fast are you swimming, walking, riding or flying."] = ""
L["Speed"] = ""

--[[ stuff ]]
L["Quit Game"] = ""
L["Stuff"] = ""
L["Switch window/fullscreen mode"] = ""
L["Windowed / Fullscreen"] = ""

--[[ surprise ]]
L["(Unknown)"] = ""
L["(finished)"] = ""
L["No item found."] = ""
L["Surprise"] = ""

--[[ tracking ]]
L["Broker to show what you are currently tracking. You can also change the tracking types from this broker."] = ""
L["Display one of the selected tracking options in broker text."] = ""
L["Display selection"] = ""
L["Hide blizzard's tracking button on minimap"] = ""
L["Hide minimap button"] = ""
L["No tracking option active."] = ""
L["Open tracking menu"] = ""
L["Tracking"] = ""

--[[ volume ]]
L["Change Volumes and toogle some audio options."] = ""
L["Change the stepping of volume changes."] = ""
L["Display in tooltip a list of your sound output hardware."] = ""
L["List of hardware"] = ""
L["Louder"] = ""
L["Mousewheel"] = ""
L["On/Off"] = ""
L["Quieter"] = ""
L["Sorry, In combat lockdown."] = ""
L["Steps"] = ""
L["Use MouseWheel"] = ""
L["Use the MouseWheel to change the volume"] = ""
L["Volume"] = ""

--[[ xp ]]
L["Back"] = ""
L["Broker to show your xp. Can be shown either as a percentage, or as values."] = ""
L["Chars under %d only"] = ""
L["Chest"] = ""
L["Delete a character from the list"] = ""
L["Display XP in broker"] = ""
L["Display a list of my chars on same realm with her level and xp"] = ""
L["Head"] = ""
L["Legs"] = ""
L["Only display my chars under max player level."] = ""
L["Out of Level"] = ""
L["Recruite a Friend"] = ""
L["Rest"] = ""
L["Ring1"] = ""
L["Ring2"] = ""
L["Select to show XP as an absolute value; Deselected will show it as a percentage."] = ""
L["Shoulder"] = ""
L["Show other chars xp"] = ""
L["Switch mode"] = ""
L["Til Next Level"] = ""
L["XP bonus"] = ""
L["XP gain disabled"] = ""
L["Your other chars (%s)"] = ""
L["not equipped"] = ""
